### ISSUE TITLE
Create component: Paragraph

### ISSUE THREAD

**Issue by stt-tomahl** [SKF/ferris#117]
Should we set margin:0 on paragraphs in the global CSS?

**Comment by raggeju** [comment]
Not too fond of this component called "Text". Shouldn't text be able to live pretty much anywhere? When adding elements with some bare text its easy to just use <span> or <p> or something without the need of a third party component.

**Comment by tobiasljungstrom** [comment]
I too have trouble seeing the use case for a text component.
