### ISSUE TITLE
Name the component library

### ISSUE THREAD

**Issue by tobiasljungstrom** [SKF/ferris#13]
The component library should have a nice marketable name. This servers several purposes:
- It makes the lib more of a product, and can incline both devs, designers, and manageres to think about it in that way.
- A nice packaging makes the product seem polished and genuine, and thus drives adoption and usage
- It's fun

**Comment by stt-tomahl** [comment]
Bearinger
BearingUI
StyleKit

**Comment by tobiasljungstrom** [comment]
Skaffold (because SKF)
Spinster
Rotato
Blue Steel

**Comment by tobiasljungstrom** [comment]
Something alluding a ferris wheel? Like the SKF wheel in Liseberg, with all its components held together by the great breaing in the center.

**Comment by stt-tomahl** [comment]
> Something alluding a ferris wheel? Like the SKF wheel in Liseberg, with all its components held together by the great breaing in the center.


![image](https://user-images.githubusercontent.com/80753901/116971899-8e866900-acba-11eb-94a3-b3263bb8b117.png)

**Comment by tobiasljungstrom** [comment]
SKF Ferris (or just Ferris)
