### ISSUE TITLE
Set up Storybook -> DSM integration

### ISSUE THREAD

**Issue by tobiasljungstrom** [SKF/ferris#47]
See https://github.com/skfccoe/design-system, the script `dsm:publish` for the established setup.
DSM documentation: https://skf.invisionapp.com/dsm/ab-skf/4-web-applications/settings?page=liveComponentsOverview

**Comment by stt-tomahl** [comment]
Is this task same as "tokens:refresh"?

**Comment by tobiasljungstrom** [comment]
It seems that the the easiest way to do this is to link DSM to our Storybook hosted on Chromatic. It was quite easy to do, and here is an example of how it looks (the Ferris tab): https://skf.invisionapp.com/dsm/ab-skf/4-web-applications/nav/5fa7caf78c01200018354495/asset/5ea6d694c465cf539ec0543e/tab/design?mode=edit This requires no api keys or scripts, and since we are already getting sb hostting in Chromatic this seems like the best way.

I'll close this now, and if it turns out that the other option - to host the stories in DSM - is better then we can revisit the topic.

**Comment by tobiasljungstrom** [comment]
Oh, and its pulling from the develop branch in Chromatic atm. When we make our first release and merge to main later, we should point all the urls to the main branch in Chromatic.
