### ISSUE TITLE
Create component: SelectField

### ISSUE THREAD

**Issue by ghost** [SKF/ferris#77]
## Acceptance criteria:
- Looks and works like its equivalent in UI-components (within reason, the purpose is to make a functional base)
- Has stories for all visual variants
- Has unit tests
- Needs "Select" atom

## Not in scope
- Uses tokens from DSM
- Matches sketch component 100%

**Comment by tobiasljungstrom** [comment]
Maybe take a look at Downshift for this one: https://github.com/downshift-js/downshift
