### ISSUE TITLE
Setup Teams->Github integration

### ISSUE THREAD

**Issue by tobiasljungstrom** [SKF/ferris#87]
We need a team mail to set this up properly. This can only be created by someone with the priviliges set. To access the page where these priviliges can be requested you need to be in the office or have access to VPN. I (raggeju) have requested VPN from Rikard on appointment from the SKF Tech support... waiting for response...

(Some date):
We have tried setting up teams without the team email but to no avail. Seems you need extra permissions to the github SKF organization.

2021-06-10:
We are getting help with this from someone called Sven Vollbehr. He is a busy man. Awaiting his response...

2021-06-16:
The torch has been passed to Martin Oehleen who will now help us out with this

**Comment by raggeju** [comment]
Some progress has been made without a team email but seems we might need heightened permissions for SKF-org in github... working on it..
